# Gruvbox Material omarchy theme
# Based on gruvbox-material by sainnhe (https://github.com/sainnhe/gruvbox-material)

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282828"

# Main text color
theme[main_fg]="#a89984"

# Title color for boxes
theme[title]="#ebdbb2"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e78a4e"

# Background color of selected items
theme[selected_bg]="#282828"

# Foreground color of selected items
theme[selected_fg]="#e78a4e"

# Color of inactive/disabled text
theme[inactive_fg]="#282828"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#585858"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a9b665"

# Cpu box outline color
theme[cpu_box]="#a89984"

# Memory/disks box outline color
theme[mem_box]="#a89984"

# Net up/down box outline color
theme[net_box]="#a89984"

# Processes box outline color
theme[proc_box]="#a89984"

# Box divider line and small boxes line color
theme[div_line]="#a89984"

# Temperature graph colors
theme[temp_start]="#7daea3"
theme[temp_mid]="#d3869b"
theme[temp_end]="#ea6962"

# CPU graph colors
theme[cpu_start]="#a9b665"
theme[cpu_mid]="#d8a657"
theme[cpu_end]="#ea6962"

# Mem/Disk free meter
theme[free_start]="#4e5900"
theme[free_mid]=""
theme[free_end]="#a9b665"

# Mem/Disk cached meter
theme[cached_start]="#7daea3"
theme[cached_mid]=""
theme[cached_end]="#89b482"

# Mem/Disk available meter
theme[available_start]="#e78a4e"
theme[available_mid]=""
theme[available_end]="#d8a657"

# Mem/Disk used meter
theme[used_start]="#ea6962"
theme[used_mid]=""
theme[used_end]="#ea6962"

# Download graph colors
theme[download_start]="#3d4070"
theme[download_mid]="#7daea3"
theme[download_end]="#89b482"

# Upload graph colors
theme[upload_start]="#701c45"
theme[upload_mid]="#d3869b"
theme[upload_end]="#d3869b"
